// Package audit provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package audit

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	AuthorizationHeaderScopes = "AuthorizationHeader.Scopes"
)

// Empty defines model for .
type Empty = interface{}

// GetAuditEventListRequest defines model for GetAuditEventListRequest.
type GetAuditEventListRequest struct {
	EventCode          *string `json:"eventCode,omitempty"`
	EventTimestampFrom *string `json:"eventTimestampFrom,omitempty"`
	EventTimestampTo   *string `json:"eventTimestampTo,omitempty"`
	EventType          *string `json:"eventType,omitempty"`
	Page               *int    `json:"page,omitempty"`
	PerPage            *int    `json:"perPage,omitempty"`
	RequestUrl         *string `json:"requestUrl,omitempty"`
	ServerIdentifier   *string `json:"serverIdentifier,omitempty"`
	UserId             *string `json:"userId,omitempty"`
	UserIp             *string `json:"userIp,omitempty"`
	UserOrganizationId *string `json:"userOrganizationId,omitempty"`
	UserPersonCode     *string `json:"userPersonCode,omitempty"`
}

// GetAuditItemsExportRequest defines model for GetAuditItemsExportRequest.
type GetAuditItemsExportRequest struct {
	EventCode          *string `json:"eventCode,omitempty"`
	EventTimestampFrom *string `json:"eventTimestampFrom,omitempty"`
	EventTimestampTo   *string `json:"eventTimestampTo,omitempty"`
	EventType          *string `json:"eventType,omitempty"`
	RequestUrl         *string `json:"requestUrl,omitempty"`
	ServerIdentifier   *string `json:"serverIdentifier,omitempty"`
	UserId             *string `json:"userId,omitempty"`
	UserIp             *string `json:"userIp,omitempty"`
	UserOrganizationId *string `json:"userOrganizationId,omitempty"`
	UserPersonCode     *string `json:"userPersonCode,omitempty"`
}

// GetPersonAuditEventListRequest defines model for GetPersonAuditEventListRequest.
type GetPersonAuditEventListRequest struct {
	EventCode          *string `json:"eventCode,omitempty"`
	EventTimestampFrom *string `json:"eventTimestampFrom,omitempty"`
	EventTimestampTo   *string `json:"eventTimestampTo,omitempty"`
	EventType          *string `json:"eventType,omitempty"`
	Page               *int    `json:"page,omitempty"`
	PerPage            *int    `json:"perPage,omitempty"`
	PersonCode         *string `json:"personCode,omitempty"`
	RequestUrl         *string `json:"requestUrl,omitempty"`
	ServerIdentifier   *string `json:"serverIdentifier,omitempty"`
	UserId             *string `json:"userId,omitempty"`
	UserIp             *string `json:"userIp,omitempty"`
	UserOrganizationId *string `json:"userOrganizationId,omitempty"`
	UserPersonCode     *string `json:"userPersonCode,omitempty"`
}

// GetPersonAuditItemsExportRequest defines model for GetPersonAuditItemsExportRequest.
type GetPersonAuditItemsExportRequest struct {
	EventCode          *string `json:"eventCode,omitempty"`
	EventTimestampFrom *string `json:"eventTimestampFrom,omitempty"`
	EventTimestampTo   *string `json:"eventTimestampTo,omitempty"`
	EventType          *string `json:"eventType,omitempty"`
	PersonCode         *string `json:"personCode,omitempty"`
	RequestUrl         *string `json:"requestUrl,omitempty"`
	ServerIdentifier   *string `json:"serverIdentifier,omitempty"`
	UserId             *string `json:"userId,omitempty"`
	UserIp             *string `json:"userIp,omitempty"`
	UserOrganizationId *string `json:"userOrganizationId,omitempty"`
	UserPersonCode     *string `json:"userPersonCode,omitempty"`
}

// DeleteAuditEventsParams defines parameters for DeleteAuditEvents.
type DeleteAuditEventsParams struct {
	// Type Type of audit to delete (1 for action audits, 2 for person audits)
	Type int32 `form:"type" json:"type"`

	// Months Retention period in months
	Months int32 `form:"months" json:"months"`
}

// SaveAuditEventJSONBody defines parameters for SaveAuditEvent.
type SaveAuditEventJSONBody = []struct {
	EventCode        *string    `json:"eventCode,omitempty"`
	EventDescription *string    `json:"eventDescription,omitempty"`
	EventSuccessful  *bool      `json:"eventSuccessful,omitempty"`
	EventTimestamp   *time.Time `json:"eventTimestamp,omitempty"`
	EventType        *string    `json:"eventType,omitempty"`
	PersonAuditData  *[]struct {
		FullName   *string `json:"fullName,omitempty"`
		PersonCode *string `json:"personCode,omitempty"`
	} `json:"personAuditData,omitempty"`
	RequestContent       *string `json:"requestContent,omitempty"`
	RequestUrl           *string `json:"requestUrl,omitempty"`
	ResponseContent      *string `json:"responseContent,omitempty"`
	ServerIdentifier     *string `json:"serverIdentifier,omitempty"`
	TransactionId        *string `json:"transactionId,omitempty"`
	UserFullName         *string `json:"userFullName,omitempty"`
	UserId               *string `json:"userId,omitempty"`
	UserIp               *string `json:"userIp,omitempty"`
	UserOrganizationCode *string `json:"userOrganizationCode,omitempty"`
	UserOrganizationId   *string `json:"userOrganizationId,omitempty"`
	UserOrganizationName *string `json:"userOrganizationName,omitempty"`
	UserPersonCode       *string `json:"userPersonCode,omitempty"`
	UserRight            *string `json:"userRight,omitempty"`
	UserRightsLevel      *int    `json:"userRightsLevel,omitempty"`
	UserRoleId           *string `json:"userRoleId,omitempty"`
	UserRoleName         *string `json:"userRoleName,omitempty"`
	UserSessionId        *string `json:"userSessionId,omitempty"`
}

// SaveAuditEventParams defines parameters for SaveAuditEvent.
type SaveAuditEventParams struct {
	// XAPIKEY API key
	XAPIKEY string `json:"X-API-KEY"`
}

// SaveAuditEventJSONRequestBody defines body for SaveAuditEvent for application/json ContentType.
type SaveAuditEventJSONRequestBody = SaveAuditEventJSONBody

// GetAuditEventListJSONRequestBody defines body for GetAuditEventList for application/json ContentType.
type GetAuditEventListJSONRequestBody = GetAuditEventListRequest

// PostApi10ListExportJSONRequestBody defines body for PostApi10ListExport for application/json ContentType.
type PostApi10ListExportJSONRequestBody = GetAuditItemsExportRequest

// GetPersonAuditEventListJSONRequestBody defines body for GetPersonAuditEventList for application/json ContentType.
type GetPersonAuditEventListJSONRequestBody = GetPersonAuditEventListRequest

// PostApi10PersonListExportJSONRequestBody defines body for PostApi10PersonListExport for application/json ContentType.
type PostApi10PersonListExportJSONRequestBody = GetPersonAuditItemsExportRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// DeleteAuditEvents request
	DeleteAuditEvents(ctx context.Context, params *DeleteAuditEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SaveAuditEventWithBody request with any body
	SaveAuditEventWithBody(ctx context.Context, params *SaveAuditEventParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SaveAuditEvent(ctx context.Context, params *SaveAuditEventParams, body SaveAuditEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAuditEventListWithBody request with any body
	GetAuditEventListWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GetAuditEventList(ctx context.Context, body GetAuditEventListJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApi10ListExportWithBody request with any body
	PostApi10ListExportWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApi10ListExport(ctx context.Context, body PostApi10ListExportJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAuditItem request
	GetAuditItem(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPersonAuditEventListWithBody request with any body
	GetPersonAuditEventListWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GetPersonAuditEventList(ctx context.Context, body GetPersonAuditEventListJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApi10PersonListExportWithBody request with any body
	PostApi10PersonListExportWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApi10PersonListExport(ctx context.Context, body PostApi10PersonListExportJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPersonAuditItem request
	GetPersonAuditItem(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) DeleteAuditEvents(ctx context.Context, params *DeleteAuditEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAuditEventsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SaveAuditEventWithBody(ctx context.Context, params *SaveAuditEventParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSaveAuditEventRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SaveAuditEvent(ctx context.Context, params *SaveAuditEventParams, body SaveAuditEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSaveAuditEventRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAuditEventListWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAuditEventListRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAuditEventList(ctx context.Context, body GetAuditEventListJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAuditEventListRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApi10ListExportWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApi10ListExportRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApi10ListExport(ctx context.Context, body PostApi10ListExportJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApi10ListExportRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAuditItem(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAuditItemRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPersonAuditEventListWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPersonAuditEventListRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPersonAuditEventList(ctx context.Context, body GetPersonAuditEventListJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPersonAuditEventListRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApi10PersonListExportWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApi10PersonListExportRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApi10PersonListExport(ctx context.Context, body PostApi10PersonListExportJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApi10PersonListExportRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPersonAuditItem(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPersonAuditItemRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewDeleteAuditEventsRequest generates requests for DeleteAuditEvents
func NewDeleteAuditEventsRequest(server string, params *DeleteAuditEventsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/1.0/delete")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "type", runtime.ParamLocationQuery, params.Type); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "months", runtime.ParamLocationQuery, params.Months); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSaveAuditEventRequest calls the generic SaveAuditEvent builder with application/json body
func NewSaveAuditEventRequest(server string, params *SaveAuditEventParams, body SaveAuditEventJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSaveAuditEventRequestWithBody(server, params, "application/json", bodyReader)
}

// NewSaveAuditEventRequestWithBody generates requests for SaveAuditEvent with any type of body
func NewSaveAuditEventRequestWithBody(server string, params *SaveAuditEventParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/1.0/event")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, params.XAPIKEY)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-API-KEY", headerParam0)

	}

	return req, nil
}

// NewGetAuditEventListRequest calls the generic GetAuditEventList builder with application/json body
func NewGetAuditEventListRequest(server string, body GetAuditEventListJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGetAuditEventListRequestWithBody(server, "application/json", bodyReader)
}

// NewGetAuditEventListRequestWithBody generates requests for GetAuditEventList with any type of body
func NewGetAuditEventListRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/1.0/list")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostApi10ListExportRequest calls the generic PostApi10ListExport builder with application/json body
func NewPostApi10ListExportRequest(server string, body PostApi10ListExportJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApi10ListExportRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApi10ListExportRequestWithBody generates requests for PostApi10ListExport with any type of body
func NewPostApi10ListExportRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/1.0/list/export")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetAuditItemRequest generates requests for GetAuditItem
func NewGetAuditItemRequest(server string, id int32) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/1.0/list/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPersonAuditEventListRequest calls the generic GetPersonAuditEventList builder with application/json body
func NewGetPersonAuditEventListRequest(server string, body GetPersonAuditEventListJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGetPersonAuditEventListRequestWithBody(server, "application/json", bodyReader)
}

// NewGetPersonAuditEventListRequestWithBody generates requests for GetPersonAuditEventList with any type of body
func NewGetPersonAuditEventListRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/1.0/person-list")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostApi10PersonListExportRequest calls the generic PostApi10PersonListExport builder with application/json body
func NewPostApi10PersonListExportRequest(server string, body PostApi10PersonListExportJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApi10PersonListExportRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApi10PersonListExportRequestWithBody generates requests for PostApi10PersonListExport with any type of body
func NewPostApi10PersonListExportRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/1.0/person-list/export")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetPersonAuditItemRequest generates requests for GetPersonAuditItem
func NewGetPersonAuditItemRequest(server string, id int32) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/1.0/person-list/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// DeleteAuditEventsWithResponse request
	DeleteAuditEventsWithResponse(ctx context.Context, params *DeleteAuditEventsParams, reqEditors ...RequestEditorFn) (*DeleteAuditEventsResponse, error)

	// SaveAuditEventWithBodyWithResponse request with any body
	SaveAuditEventWithBodyWithResponse(ctx context.Context, params *SaveAuditEventParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SaveAuditEventResponse, error)

	SaveAuditEventWithResponse(ctx context.Context, params *SaveAuditEventParams, body SaveAuditEventJSONRequestBody, reqEditors ...RequestEditorFn) (*SaveAuditEventResponse, error)

	// GetAuditEventListWithBodyWithResponse request with any body
	GetAuditEventListWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetAuditEventListResponse, error)

	GetAuditEventListWithResponse(ctx context.Context, body GetAuditEventListJSONRequestBody, reqEditors ...RequestEditorFn) (*GetAuditEventListResponse, error)

	// PostApi10ListExportWithBodyWithResponse request with any body
	PostApi10ListExportWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApi10ListExportResponse, error)

	PostApi10ListExportWithResponse(ctx context.Context, body PostApi10ListExportJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApi10ListExportResponse, error)

	// GetAuditItemWithResponse request
	GetAuditItemWithResponse(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*GetAuditItemResponse, error)

	// GetPersonAuditEventListWithBodyWithResponse request with any body
	GetPersonAuditEventListWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetPersonAuditEventListResponse, error)

	GetPersonAuditEventListWithResponse(ctx context.Context, body GetPersonAuditEventListJSONRequestBody, reqEditors ...RequestEditorFn) (*GetPersonAuditEventListResponse, error)

	// PostApi10PersonListExportWithBodyWithResponse request with any body
	PostApi10PersonListExportWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApi10PersonListExportResponse, error)

	PostApi10PersonListExportWithResponse(ctx context.Context, body PostApi10PersonListExportJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApi10PersonListExportResponse, error)

	// GetPersonAuditItemWithResponse request
	GetPersonAuditItemWithResponse(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*GetPersonAuditItemResponse, error)
}

type DeleteAuditEventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Empty
}

// Status returns HTTPResponse.Status
func (r DeleteAuditEventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAuditEventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SaveAuditEventResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Empty
}

// Status returns HTTPResponse.Status
func (r SaveAuditEventResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SaveAuditEventResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAuditEventListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Empty
}

// Status returns HTTPResponse.Status
func (r GetAuditEventListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAuditEventListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApi10ListExportResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostApi10ListExportResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApi10ListExportResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAuditItemResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Empty
}

// Status returns HTTPResponse.Status
func (r GetAuditItemResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAuditItemResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPersonAuditEventListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Empty
}

// Status returns HTTPResponse.Status
func (r GetPersonAuditEventListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPersonAuditEventListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApi10PersonListExportResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostApi10PersonListExportResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApi10PersonListExportResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPersonAuditItemResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Empty
}

// Status returns HTTPResponse.Status
func (r GetPersonAuditItemResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPersonAuditItemResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// DeleteAuditEventsWithResponse request returning *DeleteAuditEventsResponse
func (c *ClientWithResponses) DeleteAuditEventsWithResponse(ctx context.Context, params *DeleteAuditEventsParams, reqEditors ...RequestEditorFn) (*DeleteAuditEventsResponse, error) {
	rsp, err := c.DeleteAuditEvents(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAuditEventsResponse(rsp)
}

// SaveAuditEventWithBodyWithResponse request with arbitrary body returning *SaveAuditEventResponse
func (c *ClientWithResponses) SaveAuditEventWithBodyWithResponse(ctx context.Context, params *SaveAuditEventParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SaveAuditEventResponse, error) {
	rsp, err := c.SaveAuditEventWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSaveAuditEventResponse(rsp)
}

func (c *ClientWithResponses) SaveAuditEventWithResponse(ctx context.Context, params *SaveAuditEventParams, body SaveAuditEventJSONRequestBody, reqEditors ...RequestEditorFn) (*SaveAuditEventResponse, error) {
	rsp, err := c.SaveAuditEvent(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSaveAuditEventResponse(rsp)
}

// GetAuditEventListWithBodyWithResponse request with arbitrary body returning *GetAuditEventListResponse
func (c *ClientWithResponses) GetAuditEventListWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetAuditEventListResponse, error) {
	rsp, err := c.GetAuditEventListWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAuditEventListResponse(rsp)
}

func (c *ClientWithResponses) GetAuditEventListWithResponse(ctx context.Context, body GetAuditEventListJSONRequestBody, reqEditors ...RequestEditorFn) (*GetAuditEventListResponse, error) {
	rsp, err := c.GetAuditEventList(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAuditEventListResponse(rsp)
}

// PostApi10ListExportWithBodyWithResponse request with arbitrary body returning *PostApi10ListExportResponse
func (c *ClientWithResponses) PostApi10ListExportWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApi10ListExportResponse, error) {
	rsp, err := c.PostApi10ListExportWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApi10ListExportResponse(rsp)
}

func (c *ClientWithResponses) PostApi10ListExportWithResponse(ctx context.Context, body PostApi10ListExportJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApi10ListExportResponse, error) {
	rsp, err := c.PostApi10ListExport(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApi10ListExportResponse(rsp)
}

// GetAuditItemWithResponse request returning *GetAuditItemResponse
func (c *ClientWithResponses) GetAuditItemWithResponse(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*GetAuditItemResponse, error) {
	rsp, err := c.GetAuditItem(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAuditItemResponse(rsp)
}

// GetPersonAuditEventListWithBodyWithResponse request with arbitrary body returning *GetPersonAuditEventListResponse
func (c *ClientWithResponses) GetPersonAuditEventListWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetPersonAuditEventListResponse, error) {
	rsp, err := c.GetPersonAuditEventListWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPersonAuditEventListResponse(rsp)
}

func (c *ClientWithResponses) GetPersonAuditEventListWithResponse(ctx context.Context, body GetPersonAuditEventListJSONRequestBody, reqEditors ...RequestEditorFn) (*GetPersonAuditEventListResponse, error) {
	rsp, err := c.GetPersonAuditEventList(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPersonAuditEventListResponse(rsp)
}

// PostApi10PersonListExportWithBodyWithResponse request with arbitrary body returning *PostApi10PersonListExportResponse
func (c *ClientWithResponses) PostApi10PersonListExportWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApi10PersonListExportResponse, error) {
	rsp, err := c.PostApi10PersonListExportWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApi10PersonListExportResponse(rsp)
}

func (c *ClientWithResponses) PostApi10PersonListExportWithResponse(ctx context.Context, body PostApi10PersonListExportJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApi10PersonListExportResponse, error) {
	rsp, err := c.PostApi10PersonListExport(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApi10PersonListExportResponse(rsp)
}

// GetPersonAuditItemWithResponse request returning *GetPersonAuditItemResponse
func (c *ClientWithResponses) GetPersonAuditItemWithResponse(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*GetPersonAuditItemResponse, error) {
	rsp, err := c.GetPersonAuditItem(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPersonAuditItemResponse(rsp)
}

// ParseDeleteAuditEventsResponse parses an HTTP response from a DeleteAuditEventsWithResponse call
func ParseDeleteAuditEventsResponse(rsp *http.Response) (*DeleteAuditEventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAuditEventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Empty
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseSaveAuditEventResponse parses an HTTP response from a SaveAuditEventWithResponse call
func ParseSaveAuditEventResponse(rsp *http.Response) (*SaveAuditEventResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SaveAuditEventResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Empty
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetAuditEventListResponse parses an HTTP response from a GetAuditEventListWithResponse call
func ParseGetAuditEventListResponse(rsp *http.Response) (*GetAuditEventListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAuditEventListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Empty
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostApi10ListExportResponse parses an HTTP response from a PostApi10ListExportWithResponse call
func ParsePostApi10ListExportResponse(rsp *http.Response) (*PostApi10ListExportResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApi10ListExportResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetAuditItemResponse parses an HTTP response from a GetAuditItemWithResponse call
func ParseGetAuditItemResponse(rsp *http.Response) (*GetAuditItemResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAuditItemResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Empty
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetPersonAuditEventListResponse parses an HTTP response from a GetPersonAuditEventListWithResponse call
func ParseGetPersonAuditEventListResponse(rsp *http.Response) (*GetPersonAuditEventListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPersonAuditEventListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Empty
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostApi10PersonListExportResponse parses an HTTP response from a PostApi10PersonListExportWithResponse call
func ParsePostApi10PersonListExportResponse(rsp *http.Response) (*PostApi10PersonListExportResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApi10PersonListExportResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetPersonAuditItemResponse parses an HTTP response from a GetPersonAuditItemWithResponse call
func ParseGetPersonAuditItemResponse(rsp *http.Response) (*GetPersonAuditItemResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPersonAuditItemResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Empty
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
