version: "2"
run:
  go: "1.26"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - dupword
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - fatcontext
    - gocheckcompilerdirectives
    - gochecksumtype
    - godot
    - gosec
    - gosmopolitan
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nilerr
    - nilnesserr
    - noctx
    - paralleltest
    - perfsprint
    - prealloc
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unparam
    - usetesting
    - zerologlint
  disable:
    - containedctx
    - depguard
    - err113
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godox
    - interfacebloat
    - ireturn
    - lll
    - mnd
    - nilnil
    - tagalign
    - varnamelen
    - wrapcheck
  settings:
    gosec:
      excludes:
        - G117
        - G704
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: the type name `ErrorResponse` should conform to the `XxxError` format
    paths:
      - .*_test\.go$
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - prefix(github.com/lx-lib/lx-idauth)
        - default
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - .*_test\.go$
      - third_party$
      - builtin$
      - examples$
